# Generated by Django 5.1.3 on 2025-02-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
