# Generated by Django 5.1.3 on 2025-01-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(choices=[('default_profile_pics/_1.png', 'default_profile_pics/_1.png'), ('default_profile_pics/_2.png', 'default_profile_pics/_2.png'), ('default_profile_pics/_3.png', 'default_profile_pics/_3.png'), ('default_profile_pics/_4.png', 'default_profile_pics/_4.png'), ('default_profile_pics/_5.png', 'default_profile_pics/_5.png'), ('default_profile_pics/_6.png', 'default_profile_pics/_6.png')], max_length=100),
        ),
    ]
